branches:
  only:
    - master

language: ruby
rvm:
  - 2.3.1

services:
  - postgresql

script:
  - gem install 'pg'
  - apt-get update
  - bundle install
  - RAILS_ENV=test bundle exec rake db:create db:migrate db:schema:load --trace
  - bundle exec rspec

